pipeline{
    agent any

    stages{
        stage('Checkout') {
            steps {
                git credentialsId: 'svc_git_cred', poll: false, url: 'https://github.com/balujaddu/Ecom-app.git';
            }
        }
        stage('Build'){
            steps{
                echo 'Building java project';
                bat "mvn clean package";
            }
        }
        stage('Code Quality'){
            steps{
                echo 'scaning the code with SonarQube';
                withSonarQubeEnv(installationName: 'SonarQube-9.2', credentialsId: 'svc_sonar_token') {
                    bat 'mvn sonar:sonar';
                }
            }
        }
        stage('Build Management'){
            steps{
                echo 'Uploading artifacts to jfrog artifactory';
                archiveArtifacts artifacts: 'target/*.war', followSymlinks: 'false';
            }
        }
        stage('Deployment'){
            steps{
                echo 'Deploying war file to the tomcat server';
                deploy adapters: [tomcat9(credentialsId: 'svc_tomcat_cred', path: '/webapps', url: 'http://localhost:8085')], contextPath: '/app', war: 'target/*.war';
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}